# ==================================================
# Application
# ==================================================
spring.application.name=auth-service
server.port=8081


# ==================================================
# Database - PostgreSQL
# ==================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/starterkit}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sa}


# ==================================================
# JPA / Hibernate
# ==================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=auth


# ==================================================
# Flyway
# ==================================================
spring.flyway.enabled=true
spring.flyway.default-schema=auth
spring.flyway.schemas=auth


# ==================================================
# OpenAPI / Swagger
# ==================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.show-actuator=false


# ==================================================
# Log
# ==================================================
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.com.starterkit.auth.shared.infrastructure.jwt=TRACE

# ==================================================
# CORS
# ==================================================
cors.allowed-origins=http://localhost:5173


# ==================================================
# Default Admin (dev only - remove before production)
# ==================================================
app.default-admin.enabled=true
app.default-admin.username=admin
app.default-admin.password=admin123
app.default-admin.email=admin@starterkit.local


# ==================================================
# RabbitMQ
# ==================================================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin}

# ==================================================
# Event Publishing
# ==================================================
app.events.enabled=true


# ==================================================
# Transactional Outbox
# ==================================================
outbox.enabled=true
outbox.exchange=starterkit.events
outbox.source-service=auth-service
outbox.retention-days=7

outbox.publisher.enabled=true
outbox.publisher.interval-ms=5000
outbox.publisher.batch-size=100
