# ==================================================
# Application
# ==================================================
spring.application.name=auth-service
server.port=8081


# ==================================================
# Database - PostgreSQL
# ==================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/starterkit
spring.datasource.username=sa
spring.datasource.password=sa


# ==================================================
# JPA / Hibernate
# ==================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=auth


# ==================================================
# Flyway
# ==================================================
spring.flyway.enabled=true
spring.flyway.default-schema=auth
spring.flyway.schemas=auth


# ==================================================
# OpenAPI / Swagger
# ==================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.show-actuator=false


# ==================================================
# Log
# ==================================================
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.com.starterkit.auth.shared.infrastructure.jwt=TRACE

# ==================================================
# CORS
# ==================================================
cors.allowed-origins=http://localhost:5173


# ==================================================
# Default Admin (dev only - remove before production)
# ==================================================
app.default-admin.enabled=true
app.default-admin.username=admin
app.default-admin.password=admin123
app.default-admin.email=admin@starterkit.local
