# ==================================================
# Application
# ==================================================
spring.application.name=api-gateway
server.port=8080


# ==================================================
# Routes
# ==================================================
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=audit-service
spring.cloud.gateway.server.webflux.routes[1].uri=${AUDIT_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/audit/**

spring.cloud.gateway.server.webflux.routes[2].id=notif-service
spring.cloud.gateway.server.webflux.routes[2].uri=${NOTIF_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/notify/**


# ==================================================
# RabbitMQ
# ==================================================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin}


# ==================================================
# Logging
# ==================================================
logging.level.com.starterkit.gateway=INFO
logging.level.org.springframework.cloud.gateway=INFO
