# ==================================================
# Application
# ==================================================
spring.application.name=api-gateway
server.port=8080


# ==================================================
# Routes (Spring Cloud Gateway 2025 syntax)
# ==================================================
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=audit-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/audit/**


# ==================================================
# RabbitMQ
# ==================================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin


# ==================================================
# Logging
# ==================================================
logging.level.com.starterkit.gateway=INFO
logging.level.org.springframework.cloud.gateway=INFO
